### ISSUE TITLE
Custom Output Format render hooks aren't getting used

### ISSUE THREAD

**Issue by blackb1rd** [neohugo/neohugo#36]
More details: https://github.com/gohugoio/hugo/issues/7160

```toml
[outputFormats]
  [outputFormats.AppFormat]
    baseName = "index"
    name = "app"
    isPlainText = false
    mediaType = "text/html"
    isHTML = true
    permalinkable = true
    noUgly = false
    path = "app"

[outputs]
  section = ["HTML", "APP"]
  page = ["HTML", "APP"]
```

it seems any format is not getting map except `html` format as it was hardcode at function `content_map_page.go `

when removing this hardcode to process for each format, the performance was degrade, since it was also process RSS format and other things else. 
- [X] Support AMP format (For temporary fixed) #11 
- [ ] Support All format
- [ ] Change how to handle other formats
- [ ] Fix Test case related this issue
